/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.gestaoe;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author usuario
 */
public class jifTelaMenuPrincipal extends javax.swing.JInternalFrame {
    /**
     *
     */
    public static void abrir() {
        jifTelaMenuPrincipal frameInterneMenuPrincipal = new jifTelaMenuPrincipal();
               //possui o método setDefaultCloseOperation, responsável por encerrar a aplicação quando a janela for fechada
               frameInterneMenuPrincipal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               //cria um objeto chamado “tela” contendo as dimensões da tela
               Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
               //define a localização em que o frame aparecerá na tela do monitor
               frameInterneMenuPrincipal.setLocation((tela.width - frameInterneMenuPrincipal.getSize().width) / 2,
                       (tela.height - frameInterneMenuPrincipal.getSize().height) / 2);
               //torna o frame visível
               frameInterneMenuPrincipal.setVisible(true);
    }

    /**
     * Creates new form jifTelaMenuPrincipal
     */
    public jifTelaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_Cadastro = new javax.swing.JButton();
        jButton_Compras = new javax.swing.JButton();
        jButton_Estoque = new javax.swing.JButton();
        jButton_Vendas = new javax.swing.JButton();
        jButton_Caixa = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        compras = new javax.swing.JMenu();
        vendas = new javax.swing.JMenu();
        estoque = new javax.swing.JMenu();
        caixa = new javax.swing.JMenu();

        setClosable(true);
        setMaximizable(true);

        jPanelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Cadastro.setText("Cadastro");
        jButton_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroActionPerformed(evt);
            }
        });

        jButton_Compras.setText("Compras");
        jButton_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ComprasActionPerformed(evt);
            }
        });

        jButton_Estoque.setText("Estoque");
        jButton_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EstoqueActionPerformed(evt);
            }
        });

        jButton_Vendas.setText("Vendas");
        jButton_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VendasActionPerformed(evt);
            }
        });

        jButton_Caixa.setText("Caixa");
        jButton_Caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton_Compras, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton_Vendas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(jButton_Caixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(281, 281, 281))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Compras, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jButton_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jButton_Vendas, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Caixa, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(275, 275, 275))
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        cadastro.setText("Cadastro");
        MenuPrincipal.add(cadastro);

        compras.setText("Compras");
        MenuPrincipal.add(compras);

        vendas.setText("Vendas");
        MenuPrincipal.add(vendas);

        estoque.setText("Estoque");
        MenuPrincipal.add(estoque);

        caixa.setText("Caixa");
        MenuPrincipal.add(caixa);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifTelaCadastro telaCadastro = new jifTelaCadastro();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(telaCadastro);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_jButton_CadastroActionPerformed

    private void jButton_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ComprasActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifCompras telaCompras = new jifCompras();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(telaCompras);
        telaCompras.setVisible(true);
    }//GEN-LAST:event_jButton_ComprasActionPerformed

    private void jButton_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EstoqueActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifEstoque telaEstoque = new jifEstoque();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(telaEstoque);
        telaEstoque.setVisible(true);
    }//GEN-LAST:event_jButton_EstoqueActionPerformed

    private void jButton_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VendasActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifVendas telaVendas = new jifVendas();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(telaVendas);
        telaVendas.setVisible(true);
    }//GEN-LAST:event_jButton_VendasActionPerformed

    private void jButton_CaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CaixaActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifCaixa telaCaixa = new jifCaixa();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(telaCaixa);
        telaCaixa.setVisible(true);
    }//GEN-LAST:event_jButton_CaixaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenu caixa;
    private javax.swing.JMenu compras;
    private javax.swing.JMenu estoque;
    private javax.swing.JButton jButton_Cadastro;
    private javax.swing.JButton jButton_Caixa;
    private javax.swing.JButton jButton_Compras;
    private javax.swing.JButton jButton_Estoque;
    private javax.swing.JButton jButton_Vendas;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanelMenu;
    private javax.swing.JMenu vendas;
    // End of variables declaration//GEN-END:variables


//contêm o código referente ao método abrir responsável por iniciar a execução da aplicação
    /*public static void abrir() {
        jifTelaMenuPrincipal frameInterneMenuPrincipal = new jifTelaMenuPrincipal();
               //possui o método setDefaultCloseOperation, responsável por encerrar a aplicação quando a janela for fechada
               frameInterneMenuPrincipal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               //cria um objeto chamado “tela” contendo as dimensões da tela
               Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
               //define a localização em que o frame aparecerá na tela do monitor
               frameInterneMenuPrincipal.setLocation((tela.width - frameInterneMenuPrincipal.getSize().width) / 2,
                       (tela.height - frameInterneMenuPrincipal.getSize().height) / 2);
               //torna o frame visível
               frameInterneMenuPrincipal.setVisible(true);
    }*/
}
