/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.gestaoE.gestaoE;

import com.gestaoE.produto.jifCadastroProdutos;
import com.gestaoE.funcionario.jifCadastroFuncionarios;
import com.gestaoE.fornecedor.jifCadastroFornecedores;
import com.gestaoE.gestaoE.GestaoE_AreaDeTrabalho;
import com.gestaoE.cliente.jifCadastroClientes;
import static com.gestaoE.gestaoE.jifTelaMenuPrincipal.jPanelMenu;

/**
 *
 * @author usuario
 */
public class jifTelaCadastro extends javax.swing.JInternalFrame {
    private static jifTelaCadastro frameInternoLogin;

    /**
     * Creates new form NewJInternalFrame
     */
    public jifTelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTelaCadastro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_MenuCadastro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_CadastroProdutos = new javax.swing.JButton();
        jButton_CadastroClientes = new javax.swing.JButton();
        jButton_CadastroFornecedores = new javax.swing.JButton();
        jButton_CadastroFuncionarios = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Tela Cadastro");
        setToolTipText("Tela Cadastro");

        jPanelTelaCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_MenuCadastro.setText("Menu");
        jButton_MenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MenuCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_MenuCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jButton_MenuCadastro)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_CadastroProdutos.setText("Cadastro Produtos");
        jButton_CadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroProdutosActionPerformed(evt);
            }
        });

        jButton_CadastroClientes.setText("Cadastro Clientes");
        jButton_CadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroClientesActionPerformed(evt);
            }
        });

        jButton_CadastroFornecedores.setText("Cadastro Fornecedores");
        jButton_CadastroFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroFornecedoresActionPerformed(evt);
            }
        });

        jButton_CadastroFuncionarios.setText("Cadastro Funcionários");
        jButton_CadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroFuncionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_CadastroProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_CadastroFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_CadastroFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButton_CadastroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CadastroProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CadastroFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTelaCadastroLayout = new javax.swing.GroupLayout(jPanelTelaCadastro);
        jPanelTelaCadastro.setLayout(jPanelTelaCadastroLayout);
        jPanelTelaCadastroLayout.setHorizontalGroup(
            jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                .addGroup(jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTelaCadastroLayout.setVerticalGroup(
            jPanelTelaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaCadastroLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTelaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 660, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroProdutosActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifCadastroProdutos cadastrarProdutos = new jifCadastroProdutos();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(cadastrarProdutos);
        cadastrarProdutos.setVisible(true);
    }//GEN-LAST:event_jButton_CadastroProdutosActionPerformed

    private void jButton_CadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroClientesActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifCadastroClientes cadastrarClientes = new jifCadastroClientes();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(cadastrarClientes);
        cadastrarClientes.setVisible(true);
    }//GEN-LAST:event_jButton_CadastroClientesActionPerformed

    private void jButton_CadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroFornecedoresActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifCadastroFornecedores cadastrarFornecedores = new jifCadastroFornecedores();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(cadastrarFornecedores);
        cadastrarFornecedores.setVisible(true);
    }//GEN-LAST:event_jButton_CadastroFornecedoresActionPerformed

    private void jButton_CadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroFuncionariosActionPerformed
        // TODO add your handling code here:
        jPanelMenu.setVisible(false);
        jifCadastroFuncionarios cadastrarFuncionarios = new jifCadastroFuncionarios();
        GestaoE_AreaDeTrabalho.jDesktopPane1.add(cadastrarFuncionarios);
        cadastrarFuncionarios.setVisible(true);
    }//GEN-LAST:event_jButton_CadastroFuncionariosActionPerformed

    private void jButton_MenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MenuCadastroActionPerformed
        // TODO add your handling code here:
        jPanelTelaCadastro.setVisible(false);
        jifTelaMenuPrincipal menuPrincipal = new jifTelaMenuPrincipal();
            GestaoE_AreaDeTrabalho.jDesktopPane1.add(menuPrincipal);
            menuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton_MenuCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadastroClientes;
    private javax.swing.JButton jButton_CadastroFornecedores;
    private javax.swing.JButton jButton_CadastroFuncionarios;
    private javax.swing.JButton jButton_CadastroProdutos;
    private javax.swing.JButton jButton_MenuCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanelTelaCadastro;
    // End of variables declaration//GEN-END:variables
}
